version: 2
jobs:
  build:
    branches:
      only:
        - master
        - ci
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout # clone repository
      - setup_remote_docker: # setup docker env
          docker_layer_caching: true
      - run: docker login -u $docker_username -p $docker_password
      - run: chmod +x ./scripts/build.sh && ./scripts/build.sh
      - run: ssh -T $server_user@$server_address "bash -s" <./scripts/deploy.sh $bot_name $bot_token