version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout # clone repository
      - setup_remote_docker # setup docker env
      - run: chmod +x ./gradlew
      - run: ./gradlew dockerBuildImage
      - run: docker images