version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout # clone repository
      - setup_remote_docker # setup docker env
      - run: ./gradlew dockerBuildImage
      - run: docker images